# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'webinar-acr-connection'
  imageRepository: 'webinar-web-app'
  containerRegistry: 'webinaracr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

#Stages
stages:
- stage: My_Environment
  displayName: Print Params, Test, Build and Push Stage
  jobs:
  - job: Print_Parameters
    displayName: Print Parameters
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Print All Parameters:'
          echo 'Service Connection: ' $(dockerRegistryServiceConnection)
          echo '`Image Repository: ' $(imageRepository)
          echo 'Azure container Registry: ' $(containerRegistry)
          echo 'Dockerfile Path: ' $(dockerfilePath)
          echo 'Build ID: ' $(tag)
          echo 'VM Image Name: ' $(vmImageName)
  - job: Application_Tests
    displayName: Npm Install and Npm Test
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run test'