apiVersion: v1
kind: Pod
metadata:
  name: webinar-web-app
  labels:
    app: webinar-web-app
spec:
  containers:
    - name: webinar-web-app
      image: webinaracr.azurecr.io/webinar-web-app/1.0.0:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-web-app-svc
spec:
  selector:
    app: webinar-web-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
